---
# Source: ring-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-rings-v1-master
  labels:
    name: hello-rings
    version: v1
    ring: master
    group: CORE
spec:
  replicas: 1000
  selector:
    matchLabels:
      name: hello-rings
      version: v1
      ring: master
  template:
    metadata:
      labels:
        name: hello-rings
        version: v1
        ring: master
    spec:
      containers:
        - name: ring-chart
          image: "hellorings.azurecr.io/hellorings:hello-rings-featurec-5641"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
# Source: ring-chart/templates/ring.yaml
# Source: hello-ring/templates/ring.yaml
apiVersion: rings.microsoft.com/v1alpha1
kind: Ring
metadata:
  name: hello-rings-v1-master
  contact: bhargav@hellorings.com
  branchName: featurec # Set by pipeline
  buildId: 5641 # Set by pipeline
  buildDate: 2019-08-07T21:30:07.3141419Z # Set by pipeline
  commitId: 376326f02613aa0e7e826b4f1fbaa77cba62a003 # Set by pipeline
spec:
  # Deploy to environment
  deploy: true
  entryPoints:
    # Source of traffic (eg: 80 or 443)
    - http
    - https
    - internal
  routing:
    service: hello-rings
    version: v1
    branch: feature/48883-add-search
    group: CORE
    ports:
      - 8080
    initialUsers:
      - bill@contoso.com
      - ted@contoso.com

