---
# Source: hello-ring/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-rings-featurea
  labels:
    app.kubernetes.io/name: hello-rings-featurea
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-rings-featurea
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-rings-featurea
    spec:
      containers:
        - name: hello-ring
          image: "hellorings.azurecr.io/hellorings:hello-rings-featurea-3866"
          imagePullPolicy: IfNotPresent

---
# Source: hello-ring/templates/ring.yaml
apiVersion: rings.microsoft.com/v1alpha1
kind: Ring
metadata:
  name: featurea
spec:
  # Deploy to environment
  deploy: true
  # Custom Claims
  claim: featurea
  entryPoints:
    # Source of traffic (eg: 80 or 443)
    - http
    - https
    - internal
  match: PathPrefix(`/query/v1`) && Headers(`x-ring`, `featurea`)
  selector:
    app.kubernetes.io/name: hello-rings-featurea
