---
# Source: ring-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-rings-featurea-v0.1-featurea
  labels:
    name: hello-rings-featurea
    version: v0.1
    ring: featurea
    group: CORE
spec:
  replicas: 1000
  selector:
    matchLabels:
      name: hello-rings-featurea
      version: v0.1
      ring: featurea
  template:
    metadata:
      labels:
        name: hello-rings-featurea
        version: v0.1
        ring: featurea
    spec:
      containers:
        - name: ring-chart
          image: "hellorings.azurecr.io/hellorings:hello-rings-featurea-4322"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
# Source: ring-chart/templates/ring.yaml
# Source: hello-ring/templates/ring.yaml
apiVersion: rings.microsoft.com/v1alpha1
kind: Ring
metadata:
  name: hello-rings-featurea-v0.1-featurea
  contact: samiya@hellorings.com
  branchName: featurea # Set by pipeline
  buildId: 4322 # Set by pipeline
  buildDate: 2019-06-25T09:08:50.3790219Z # Set by pipeline
  commitId: b11b2ee250b44d25cf5e86a8b35e858af6852a9f # Set by pipeline
spec:
  # Deploy to environment
  deploy: true
  entryPoints:
    # Source of traffic (eg: 80 or 443)
    - http
    - https
    - internal
  routing:
    service: hello-rings-featurea
    version: v0.1
    branch: feature/48883-add-search
    group: CORE
    ports:
      - 8080
    initialUsers:
      - bill@contoso.com
      - ted@contoso.com

